server:
  port: 8888
spring:
  application:
    name: FileManage
  server:
    MaxFileSize: 300MB
    MaxRequestSize: 500MB

seafile:
  baseUrl: 10.12.37.209
  api:
    ping: http://${seafile.baseUrl}:8000/api2/ping/
    obtainAuthToken: http://${seafile.baseUrl}:8000/api2/auth-token/ #获取用户token接口
    account: http://${seafile.baseUrl}:8000/api2/accounts/ #对帐户进行CURD的接口





