
server:
  port: 8888
spring:
  application:
    name: FileManage

seafile:
  baseUrl: http://10.12.36.165:8000
  user: test@123.com
  password: 123123
  #file:
  api:
    ping: http://10.12.36.165:8000/api2/ping/
    obtainAuthToken: http://10.12.36.165:8000/api2/auth-token/
    #getLibraryInfo:
    getUploadLink: http://10.12.36.165:8000/api2/repos/dea61fa4-1f96-457c-ba27-4e7b477c6fbc/upload-link/
  library:
    repoId: dea61fa4-1f96-457c-ba27-4e7b477c6fbc #music


