server:
  port: 8888
spring:
  application:
    name: FileManage

seafile:
  baseUrl: 10.12.37.209
  api:
    ping: http://${seafile.baseUrl}:8000/api2/ping/
    obtainAuthToken: http://${seafile.baseUrl}:8000/api2/auth-token/ #获取用户token接口
    getUploadLink: http://${seafile.baseUrl}:8000/api2/repos/dea61fa4-1f96-457c-ba27-4e7b477c6fbc/upload-link/ #获取上传链接接口
    account: http://${seafile.baseUrl}:8000/api2/accounts/ #对帐户进行CURD的接口

  library:
    repoId: dea61fa4-1f96-457c-ba27-4e7b477c6fbc #music库
    #id:



